stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  rules:
    changes:
      - "**/*.go"
  script: 
   - go test .
build:
  stage: build
  needs: []
  image: docker:latest
  script:
   - docker build .
